workflows:
  default-workflow:
    name: Default Workflow
    environment:
      flutter: stable
    cache:
      cache_paths:
        - $CM_BUILD_DIR/build
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
    scripts:
      - flutter packages pub get
      # - name: Testing Bash
      #   script: |
      #     bash test.sh
      - name: Testing Core Package
        script: |
          cd core
          flutter test --coverage
          cd ..
      - name: Testing Saerch Package
        script: |
          cd search
          flutter test --coverage
          cd ..
      - name: Build Android APK
        script: |
        flutter build apk --release
    artifacts:
      - coverage/lcov.info
      - build/**/outputs/apk/**/*.apk
