// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2U8clDOQTngq2LVNE77C1MOGKF04qnOM',
    appId: '1:575967768123:web:a0b993585cbb39a710361e',
    messagingSenderId: '575967768123',
    projectId: 'ditonton',
    authDomain: 'ditonton.firebaseapp.com',
    storageBucket: 'ditonton.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrh1fswrRPqYUCetfZKHa6eGQIEvdyjkE',
    appId: '1:575967768123:android:0c67a8f9b2438cc810361e',
    messagingSenderId: '575967768123',
    projectId: 'ditonton',
    storageBucket: 'ditonton.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTcyu4CLCtRiNOiN5DWX6ThvUZsDM5yUM',
    appId: '1:575967768123:ios:72ba0bd58803341510361e',
    messagingSenderId: '575967768123',
    projectId: 'ditonton',
    storageBucket: 'ditonton.appspot.com',
    iosClientId: '575967768123-imee5o18h5uv97ol11bfa0ivmtuk4bqq.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
